let weaponList = {
    "arcpistollvl4":{"id":"arcpistollvl4","name":"Arc Pistol, Level 4", "damage":"1d8", "damageType":"E", "critical effect":"Arc", "critical effect damage":"[[1d4]]", "toHitAttribute":"dexterity","ammo":"charge","capacity":20,"usage":2, "special":"Stun", "type":"small-arms"},
    "arcpistolstatic":{"id":"arcpistolstatic","name":"Arc Pistol, Static", "damage":"1d6", "damageType":"E", "critical effect":"Arc", "critical effect damage":"[[2]]", "toHitAttribute":"dexterity", "special":"Stun","ammo":"charge","capacity":20,"usage":2, "type":"small-arms"}, 
    "artillerylaserazimuth":{"id":"artillerylaserazimuth","name":"Artillery Laser, Azimuth", "damage":"1d10", "damageType":"F", "critical effect":"burn", "critical effect damage":"1d6", "toHitAttribute":"dexterity", "special":"Penetrating","ammo":"charge","capacity":20,"usage":2, "type":"heavy"},
    "batontactical":{"id":"batontactical","name":"Baton, tactical", "damage":"1d4", "damageType":"B", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Analog, Operative", "type":"basic-melee"}, 
    "club":{"id":"club","name":"Club", "damage":"1d6", "damageType":"B", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Analog, archaic", "type":"basic-melee"}, 
    "dogslicer":{"id":"dogslicer","name":"Dogslicer", "damage":"1d4", "damageType":"S", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Analog", "type":"basic-melee"}, 
    "duelingswordtactical":{"id":"duelingswordtactical","name":"Dueling Sword, Tactical", "damage":"1d6", "damageType":"S", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Analog", "type":"basic-melee"}, 
    "hammerassault":{"id":"hammerassault","name":"Hammer, Assault", "damage":"1d6", "damageType":"B", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Analog", "type":"advanced-melee"},
    "huchketrifle":{"id":"huchketrifle","name":"Huchket Rifle", "damage":"1d10", "damageType":"P", "critical effect":"wound", "critical effect damage":"1t[CriticalWounds]", "toHitAttribute":"dexterity","ammo":"round","capacity":6,"usage":1, "type":"longarms"}, 
    "junklaser":{"id":"junklaser","name":"Junk Laser", "damage":"1d4", "damageType":"F", "critical effect":"burn", "critical effect damage":"1d4", "toHitAttribute":"dexterity","ammo":"charge","capacity":10,"usage":1, "type":"small-arms"}, 
    "laserpistolazimuth":{"id":"laserpistolazimuth","name":"Laser Pistol, Azimuth", "damage":"1d4", "damageType":"F", "critical effect":"burn", "critical effect damage":"1d4", "toHitAttribute":"dexterity","ammo":"charge","capacity":40,"usage":1, "type":"small-arms"}, 
    "laserrifleazimuth":{"id":"laserrifleazimuth","name":"Laser Rifle, Azimuth", "damage":"1d8", "damageType":"F", "critical effect":"burn", "critical effect damage":"1d6", "toHitAttribute":"dexterity","ammo":"charge","capacity":40,"usage":2, "type":"longarms"}, 
    "longsword":{"id":"longsword","name":"Longsword", "damage":"1d8", "damageType":"S", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Analog", "type":"advanced-melee"}, 
    "scattergunutility":{"id":"scattergunutility","name":"Scattergun, Utility", "damage":"1d4", "damageType":"P", "toHitAttribute":"dexterity","ammo":"shell","capacity":4,"usage":1, "type":"longarms", "special":"Analog, blast"}, 
    "semiautopistoltactical":{"id":"semiautopistoltactical","name":"Semi-Auto Pistol, Tactical", "damage":"1d6", "damageType":"P", "toHitAttribute":"dexterity","ammo":"round","capacity":9,"usage":1, "type":"small-arms"}, 
    "shirreneyerifletactical":{"id":"shirreneyerifletactical","name":"Shirren-Eye Rifle, Tactical", "damage":"1d10", "damageType":"P", "toHitAttribute":"dexterity","ammo":"round","capacity":1,"usage":1, "type":"sniper"}, 
    "survivalknife":{"id":"survivalknife","name":"Survival Knife", "damage":"1d4", "damageType":"S", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Operative", "type":"basic-melee"}, 
    "unarmedstrike":{"id":"unarmedstrike","name":"Unarmed Strike", "damage":"1d3", "damageType":"B", "toHitAttribute":"strength", "toDamageAttribute":"strength", "special":"Archaic, nonlethal", "type":"basic-melee"}, 
};
let grenadeList = {
    "cryogrenade1":{"id":"cryogrenade1","name":"Cryo Grenade I", "level":"6", "effect":"[[1d8]] C, staggered [[1]] round, 10 ft."},
    "flashgrenade1":{"id":"flashgrenade1","name":"Flash Grenade I", "level":"2", "effect":"blinded [[1d4]] rounds, 5 ft."},
    "flashgrenade2":{"id":"flashgrenade2","name":"Flash Grenade II", "level":"6", "effect":"blinded [[1d4]] rounds, 10 ft."},
    "fraggrenade1":{"id":"fraggrenade1","name":"Frag Grenade I", "level":"1", "effect":"[[1d6]] P, 15 ft."},
    "fraggrenade2":{"id":"fraggrenade2","name":"Frag Grenade II", "level":"4", "effect":"[[2d6]] P, 15 ft."},
    "incendiarygrenade1":{"id":"incendiarygrenade1","name":"Incendiary Grenade I", "level":"2", "effect":"[[1d6]] F, [[1d4]] burn, 5 ft."},
    "incendiarygrenade2":{"id":"incendiarygrenade2","name":"Incendiary Grenade II", "level":"6", "effect":"[[2d6]] F, [[1d6]] burn, 10 ft."},
    "screamergrenade1":{"id":"screamergrenade1","name":"Screamer Grenade I", "level":"4", "effect":"[[1d10]] So, deafened [[1d4]] minutes, 15 ft."},
    "shockgrenade1":{"id":"shockgrenade1","name":"Shock Grenade I", "level":"1", "effect":"[[1d8]] E, 15 ft."},
    "shockgrenade2":{"id":"shockgrenade2","name":"Shock Grenade II", "level":"4", "effect":"[[1d12]] E, 15 ft."},
    "smokegrenade":{"id":"smokegrenade","name":"Smoke Grenade", "level":"1", "effect":"smoke cloud 1 min., 20 ft."},
    "stickybombgrenade1":{"id":"stickybombgrenade1","name":"Stickybomb Grenade I", "level":"1", "effect":"entangled [[2d4]] rounds, 10 ft."},
    "stickybombgrenade2":{"id":"stickybombgrenade2","name":"Stickybomb Grenade II", "level":"4", "effect":"entangled [[2d4]] rounds, 15 ft."},
};
